version: '3.8'
services:
  # local test mongo database
  db:
    image: mongo:6.0.5
    container_name: mongodb
    volumes:
      - ./test_database/mongod.conf:/etc/mongod.conf
      - ./test_database/logs:/var/log/mongodb/
      - ./test_database/db:/var/lib/mongodb
    command: mongod --config /etc/mongod.conf
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: testadmin
      MONGO_INITDB_ROOT_PASSWORD: password

  # Build container for portal
  portal:
    build:
      context: ./portal
    volumes:
      - ./portal:/app
      - /app/node_modules
    ports:
      - 3000:3000
    image: next_portal:app
    container_name: next_portal_app_container
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000

networks:
  db:
  portal:
