version: '3.8'
services:
  # Build container for portal
  portal:
    build:
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    image: next_portal:app
    container_name: next_portal_app_container
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
# networks:
#   portal:
