version: '3.8'
services:
  # database image

  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    image: next_portal:frontend
    container_name: next_portal_frontend_container
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000

  # backend

networks:
  frontend:
  # backend:
