import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useSession } from 'next-auth/react'

const HomePage = () => {
  const { data: session } = useSession()

  return (
    <React.Fragment>
      <Head>
        <title>USIT Portal</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <p>Homepage</p>

        <div>
          <Link href='/meeting'>Sign into meeting</Link>
          <Link href='/meeting/AddMeeting'>Add meeting</Link>
          <Link href='/membershipPaymentPage'>membership payment page</Link>
        </div>

        {session ? (
          <Link href='/profile'>profile</Link>
        ) : (
          <div>
            <Link href='/auth/SignInPage'>Sign In</Link>
            <span> | </span>
            <Link href='/auth/SignUpPage'>Sign Up</Link>
          </div>
        )}
      </main>
    </React.Fragment>
  )
}

export default HomePage
