import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <p>Homepage</p>

        {session ? (
          <Link href='/profile'>profile</Link>
        ) : (
          <div>
            <Link href='/auth/signin'>Sign In</Link>
            <span> | </span>
            <Link href='/auth/signup'>Sign Up</Link>
          </div>
        )}
      </main>
    </>
  )
}
