import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useSession } from 'next-auth/react'

const HomePage = () => {
  const { data: session } = useSession()

  return (
    <React.Fragment>
      <Head>
        <title>USIT Portal</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <p>Homepage</p>

        <div>
          <Link href='/trading/meeting-sign-in'>Sign into meeting</Link>
          <br />
          <br />

          <Link href='/trading/add-meeting'>Add meeting</Link>
          <br />
          <br />

          <Link href='/membership-payment'>membership payment page</Link>
          <br />
          <br />

          <Link href='/trading/add-vote'>Vote for pitch</Link>
          <br />
          <br />

          <Link href='/trading/add-pitch'>add pitch</Link>
          <br />
          <br />

          <Link href='/trading/add-stock'>add stock</Link>
        </div>

        {session ? (
          <Link href='/profile'>profile</Link>
        ) : (
          <div>
            <Link href='/auth/sign-in'>Sign In</Link>
            <span> | </span>
            <Link href='/auth/sign-up'>Sign Up</Link>
          </div>
        )}
      </main>
    </React.Fragment>
  )
}

export default HomePage
